# Site settings
title: Nucleo Digital
email: contato@nucleo.digital
url: https://nucleo.digital
description: "Focada em soluções para comunicação digital, buscamos fornecer a melhor experiência da gestão da sua marca no ambiente on-line, trazendo resultados efetivos."
slogan: Posicionando marcas e conectando pessoas

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  # links: '#219ab3'
  links: '#ffffff'

# Footer settings
footer: Nucleo Digital

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:  
  - title: facebook
    url: https://facebook.com/nucleo.dig
  - title: instagram
    url: https://instagram.com/digital.nucleo
  - title: linkedin
    url: https://www.linkedin.com/company/digital-nucleo

customers:
  - title: Orquídea Alimentos
    url:
  - title: Vipal Borrachas
    url:      
  - title: Fruki Guaraná
    url:    
  - title: Panvel Farmácias
    url:    
  - title: Cervejaria Bellavista
    url:    
  - title: iPlace
    url:    
  - title: Móveis Alminhana
    url: 

# Build settings
markdown: kramdown
permalink: pretty
