# Site settings
title: Nucleo Digital
email: contato@nucleo.digital
url: https://nucleo.digital
description: "Somos uma empresa focada em soluções para comunicação digital. Buscamos fornecer a melhor experiência da gestão da sua marca no ambiente on-line, trazendo resultados efetivos."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Nucleo Digital

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:  
  - title: facebook
    url: https://facebook.com/nucleo.dig
  - title: instagram
    url: https://instagram.com/digital.nucleo
  - title: linkedin
    url: 

# Build settings
markdown: kramdown
permalink: pretty
